### ISSUE TITLE
Shadowburn rank 6

### ISSUE THREAD

**Issue by drejjmit** [cloudbells/FieldGuide#1]
![image](https://user-images.githubusercontent.com/15526476/59556706-707cc600-8fc7-11e9-9245-fd0741a1d4ba.png)

**Comment by cloudbells** [comment]
I left this at 0 because I wasn't sure how much Shadowburn actually cost at 56. I don't have beta and on pservers I think they got the price wrong as it does cost 2g20s but it is the only talent in the game to cost anywhere near that much. So I need someone with beta to verify.

**Comment by LobsterBandit** [comment]
Screenshot from the class trainer in IF in the Classic Beta.

![ClassicBetaShadowburnCost](https://user-images.githubusercontent.com/12243486/59802707-86d09d80-92b7-11e9-8759-091816971bac.png)

**Comment by cloudbells** [comment]
Hey thanks for that. Are you Honored or above with the trainer's faction (I'm assuming he is with Gnomeregan Exiles) or are you rank 3 (Sergeant) or above or both? These both give 10% discount up to 20% total.

**Comment by LobsterBandit** [comment]
Correct, he is with Gnomeregan Exiles.  No PvP rank and only Friendly with them.  I am Honored with Ironforge if that may have an impact.

![ClassicBetaShadowburnCost2](https://user-images.githubusercontent.com/12243486/59803364-42460180-92b9-11e9-8626-5577f39da55c.png)

**Comment by cloudbells** [comment]
Thanks! <3
