### ISSUE TITLE
[Classic] Lua error on wow launch

### ISSUE THREAD

**Issue by Freezy3** [cloudbells/FieldGuide#2]
Message: Interface\AddOns\FieldGuide\FieldGuide.lua:185: bad argument #1 to 'ipairs' (table expected, got nil)
Time: Sat Jun 22 07:19:11 2019
Count: 1
Stack: Interface\AddOns\FieldGuide\FieldGuide.lua:185: bad argument #1 to 'ipairs' (table expected, got nil)
[C]: in function `ipairs'
Interface\AddOns\FieldGuide\FieldGuide.lua:185: in function <Interface\AddOns\FieldGuide\FieldGuide.lua:171>
Interface\AddOns\FieldGuide\FieldGuide.lua:410: in function <Interface\AddOns\FieldGuide\FieldGuide.lua:402>
Interface\AddOns\FieldGuide\FieldGuide.lua:543: in function `FieldGuide_OnEvent'
[string "*:OnEvent"]:1: in function <[string "*:OnEvent"]:1>

Locals: (*temporary) = nil
(*temporary) = "table expected, got nil"
 = <function> defined =[C]:-1

**Comment by cloudbells** [comment]
Do you happen to be a priest or shaman? :) haven't added those spells yet

If you aren't we got a problem

**Comment by Freezy3** [comment]
Yeah Priest, didn't realize. Thanks for the reply.
