### ISSUE TITLE
Hide non-race priest abilities

### ISSUE THREAD

**Issue by sinkda** [cloudbells/FieldGuide#3]
Right now you can toggle the horde abilities on priest but as a dwarf priest I still see the human / night elf abilities.

![image](https://user-images.githubusercontent.com/17501944/60019767-9efc4000-965c-11e9-9ad2-5e491cbadae9.png)

**Comment by cloudbells** [comment]
Yeah this is something I'm working on, but there are other features I'm fixing first, such as horizontal scroll. In the case of priest, at 60 there are currently 18 spells available (if you include Horde spells), and I want to be able to scroll to them. But yes, right after that I'll fix this.
