### ISSUE TITLE
Lua error for Priest last row talents

### ISSUE THREAD

**Issue by sinkda** [cloudbells/FieldGuide#5]
I get the following Lua error when I scroll to the bottom of the priest pane:

![image](https://user-images.githubusercontent.com/17501944/60020164-71fc5d00-965d-11e9-9f89-29cf9ffa9be5.png)

This only happens when "Talents" is selected.  Perhaps a missing texture for one of the talented abilities?  Though all of the abilities are there so maybe something else is trying to show but can't?

This also happens at the end (with talents selected) for Paladins but no other pane seems to bring up this Lua error.

**Comment by cloudbells** [comment]
Yep, this is because they have > 13 spells available at 60. Same at two other levels for Priests and at 60 for Paladin. I made a lazy fix for it not too long ago but I'm currently fixing the horizontal scroll which should be done very soon.
