### ISSUE TITLE
[Suggestion] Hide empty level brackets

### ISSUE THREAD

**Issue by sinkda** [cloudbells/FieldGuide#6]
Is it possible to hide empty level brackets?  It's a bit annoying to scroll past a bunch of empty rows.  They can come back when Known Spells is available of course but when it's unchecked id like to see just the abilities I have left to learn. 

![image](https://user-images.githubusercontent.com/17501944/60020507-2a2a0580-965e-11e9-9539-6ba614c6fa8f.png)

**Comment by cloudbells** [comment]
Yeah, that's also planned to be fixed :)
